version: "3.9"

services:

  db:
    image: postgres
    restart: unless-stopped
    container_name: expmotor_postgres
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - main
    env_file: .env.prod

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: [ "/app/compose/production/startup_web.sh" ]
    container_name: expmotor_web
    networks:
      - main
    ports:
      - "8000:8000"
    env_file: .env.prod
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  main:
