services:

  db:
    image: postgres
    restart: always
    container_name: expmotor_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 3
      start_period: 30s
      timeout: 10s
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - main
    env_file: .env

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ["/expmotor/compose/production/startup_web.sh"]
    container_name: expmotor_web
    restart: always
    networks:
      - main
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    restart: always
    container_name: expmotor_redis
    volumes:
      - type: volume
        source: redis_data
        target: /data
    networks:
      - main

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ["./compose/production/entrypoint_celery.sh"]
    command: celery -A settings worker -l INFO
    container_name: expmotor_celery_worker
    restart: always
    networks:
      - main
    env_file: .env
    depends_on:
      - db
      - redis
      - web

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.prod
    entrypoint: ["./compose/production/entrypoint_celery.sh"]
    command: celery -A settings beat -l INFO -S django
    container_name: expmotor_celery_beat
    restart: always
    networks:
      - main
    env_file: .env
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
  redis_data:

networks:
  main: