services:

  db:
    image: postgres
    restart: always
    container_name: expmotor_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 3
      start_period: 30s
      timeout: 10s
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - main
    env_file: .env

  web_dev:
    build: .
    command: [ "/expmotor/compose/local/startup_web.sh" ]
    container_name: expmotor_web_dev
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - main
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:

networks:
  main: