services:

  db:
    image: postgres
    restart: always
    container_name: expmotor_postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 3
      start_period: 30s
      timeout: 10s
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - main
    env_file: .dev

  web_dev:
    build: .
    command: [ "/expmotor/compose/local/startup_web.sh" ]
    container_name: expmotor_web_dev
    restart: always
    volumes:
      - type: bind
        source: .
        target: /expmotor
    networks:
      - main
    ports:
      - "8000:8000"
    env_file: .dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:alpine
    restart: always
    container_name: expmotor_redis
    volumes:
      - type: volume
        source: redis_data
        target: /data
    networks:
      - main

  celery_worker:
    build: .
    entrypoint: [ "./compose/local/entrypoint_celery.sh" ]
    command: celery -A settings worker -l INFO
    container_name: expmotor_celery_worker
    restart: always
    volumes:
      - type: bind
        source: .
        target: /expmotor
    networks:
      - main
    env_file: .dev
    depends_on:
      - db
      - redis
      - web_dev

  celery_beat:
    build: .
    entrypoint: [ "./compose/local/entrypoint_celery.sh" ]
    command: celery -A settings beat -l INFO -S django
    container_name: expmotor_celery_beat
    restart: always
    volumes:
      - type: bind
        source: .
        target: /expmotor
    networks:
      - main
    env_file: .dev
    depends_on:
      - db
      - redis
      - web_dev

volumes:
  postgres_data:
  redis_data:

networks:
  main:
