version: "3.9"

services:

  db:
    image: postgres
    restart: unless-stopped
    container_name: expmotor_postgres
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - expmotor
    env_file: .env

  web:
    build: .
    entrypoint: [ "/app/compose/local/entrypoint_web.sh" ]
    command: gunicorn settings.wsgi:application --bind 0.0.0.0:8000 --reload
    container_name: web
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - expmotor
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  expmotor:
