services:

  db:
    image: postgres
    restart: unless-stopped
    container_name: expmotor_postgres
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
    networks:
      - main
    env_file: .env

  web_dev:
    build: .
    command: [ "/app/compose/local/startup_web.sh" ]
    container_name: expmotor_web_dev
    volumes:
      - type: bind
        source: .
        target: /app
    networks:
      - main
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  main:
